apiVersion: v1
kind: ServiceAccount
metadata:
  name: gemini-eli5-client
  namespace: ai-client
---
apiVersion: v1
kind: Service
metadata:
  name: gemini-eli5-client
  namespace: ai-client
  labels:
    app: gemini-eli5-client
spec:
  ports:
  - port: 5000
    name: http
  selector:
    name: gemini-eli5-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini-eli5-client-deployment
  namespace: ai-client
  labels:
    app: gemini-eli5-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gemini-eli5-client
  template:
    metadata:
      labels:
        name: gemini-eli5-client
    spec:
      serviceAccountName: gemini-eli5-client
      containers:
      - name: gemini-eli5-client
        image: ably77/curl-ui:0.6.9
        ports:
        - containerPort: 5000
        env:
          - name: CURL_UI_TITLE
            value: "Gemini ELI5 Client"
          - name: REQUEST_URL
            value: "https://ai-gateway.demo.glooplatform.com/gemini"
          - name: BASE_PATH
            value: "/eli5"
          - name: ENABLE_JSON_CONTENT_TYPE
            value: "true"
          - name: DEFAULT_HTTP_METHOD
            value: "POST"
          - name: HEADER_1_KEY
            value: "api-key"
          - name: HEADER_1_VALUE
            value: "solo.io"
          - name: HEADER_2_KEY
            value: "x-template"
          - name: HEADER_2_VALUE
            value: "eli5"
          - name: HEADER_3_KEY
            value: "x-prompt"
          - name: HEADER_3_VALUE
            value: "What would you like me to explain like I am 5 years old?"
