apiVersion: v1
kind: ServiceAccount
metadata:
  name: openai-kubernetes-expert-client
  namespace: ai-client
---
apiVersion: v1
kind: Service
metadata:
  name: openai-kubernetes-expert-client
  namespace: ai-client
  labels:
    app: openai-kubernetes-expert-client
spec:
  ports:
  - port: 5000
    name: http
  selector:
    name: openai-kubernetes-expert-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-kubernetes-expert-client-deployment
  namespace: ai-client
  labels:
    app: openai-kubernetes-expert-client
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openai-kubernetes-expert-client
  template:
    metadata:
      labels:
        name: openai-kubernetes-expert-client
    spec:
      serviceAccountName: openai-kubernetes-expert-client
      containers:
      - name: openai-kubernetes-expert-client
        image: ably77/curl-ui:0.6.9
        ports:
        - containerPort: 5000
        env:
          - name: CURL_UI_TITLE
            value: "OpenAI Kubernetes Expert Client"
          - name: REQUEST_URL
            value: "https://ai-gateway.demo.glooplatform.com/openai"
          - name: BASE_PATH
            value: "/k8s"
          - name: ENABLE_JSON_CONTENT_TYPE
            value: "true"
          - name: DEFAULT_HTTP_METHOD
            value: "POST"
          - name: HEADER_1_KEY
            value: "x-api-key"
          - name: HEADER_1_VALUE
            value: "Input your OpenAI API key here"
          - name: HEADER_2_KEY
            value: "x-template"
          - name: HEADER_2_VALUE
            value: "system-user-input"
          - name: HEADER_3_KEY
            value: "x-system-prompt"
          - name: HEADER_3_VALUE
            value: "You are a Kubernetes Expert"
          - name: HEADER_4_KEY
            value: "x-user-prompt"
          - name: HEADER_4_VALUE
            value: "Explain to me the value of implementing a Service Mesh in my environment"
