apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: ai-gateway
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: 'mgmt'
    namespaces:
    - name: ai-gateway-ws-config
  - name: '*'
    namespaces:
    - name: openai
    - name: gemini
    - name: ai-client