apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: ai-gateway-workspacesettings
  namespace: ai-gateway-ws-config
spec:
  exportTo:
  - workspaces:
    - name: ops-team
  importFrom:
  - workspaces:
    - name: ops-team
  options:
    federation:
      enabled: true
      serviceSelector:
      - namespace: openai
      - namespace: ai-client
    serviceIsolation:               # enable service isolation and Istio Sidecar resource
      enabled: false
      trimProxyConfig: true