# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- ai-gateway-workspace.yaml
- ai-gateway-workspacesettings.yaml
- ai-gateway-ws-config-ns.yaml