apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: TransformationPolicy
metadata:
  name: gemini-language-translator-prompt-template
  namespace: ai-gateway-ws-config
spec:
  applyToRoutes:
  - route:
      labels:
        prompt-template: gemini-translator
  config:
    request:
      injaTemplate:
        # if x-api-key header is present, append variable as a query param, else route to original path
        headers:
          :path:
            text: '{% if header("x-api-key") != "" %}/gemini?key={{ api_key }}{% else %}{{ original_path }}{% endif %}'
        # input prompt template
        body:
          text: |
            {
              "contents": [
                {
                  "role": "user",
                  "parts": [
                    {
                      "text": "Translate some text for me into {{ language }}"
                    }
                  ]
                },
                {
                  "role": "model",
                  "parts": [
                    {
                      "text": "Sure I can translate that for you into {{ language }}, what would you like me to translate?"
                    }
                  ]
                },
                {
                  "role": "user",
                  "parts": [
                    {
                      "text": " {{ prompt}}"
                    }
                  ]
                }
              ],
              "generation_config": {
                "temperature": {% if header("x-temp") != "" %}{{ temperature }}{% else %}0.7{% endif %},
                "maxOutputTokens": 250
              }
            }
        extractors:
          # extracts x-language header var
          language:
            header: 'x-language'
            regex: '.*'
          # extracts x-prompt header var
          prompt:
            header: 'x-prompt'
            regex: '.*'
          # extracts x-api-key header var
          api_key:
            header: 'x-api-key'
            regex: '.*'
          # extracts pseudo-path header var
          original_path:
            header: ':path'
            regex: '.*'
          # extracts x-temp header var
          temperature:
            header: 'x-temp'
            regex: '.*'
