apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: gemini-client-extauthpolicy
  namespace: ai-gateway-ws-config
spec:
  applyToRoutes:
  - route:
      labels:
        oauth: gemini-client.central.glooplatform.com
  config:
    server:
      name: glooplatform-east-ext-auth-server
      namespace: gloo-mesh
      cluster: mgmt
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://gemini-client.central.glooplatform.com
            callbackPath: /callback
            clientId: 967359009029-j7uts17vmc85kt3aaie8cnpodefql93t.apps.googleusercontent.com
            clientSecretRef:
              name: gcp-client-secret
              namespace: gloo-mesh
            issuerUrl: https://accounts.google.com
            scopes:
            - email