apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gemini-eli5-rt
  namespace: ai-gateway-ws-config
  labels:
    llm-type: gemini
    prompt-template: "gemini-eli5"
spec:
  http:
    - name: eli5-translator
      matchers:
      - uri:
          prefix: /gemini
        headers:
        - name: x-template
          value: eli5
        - name: x-prompt
      forwardTo:
        pathRewrite: /v1beta/models/gemini-pro:generateContent
        hostRewrite: generativelanguage.googleapis.com
        destinations:
        - kind: EXTERNAL_SERVICE
          port:
            number: 443
          ref:
            name: gemini-externalservice
            namespace: ai-gateway-ws-config