apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gemini-language-transformer-rt
  namespace: ai-gateway-ws-config
spec:
  http:
    - name: language-translator
      labels:
        prompt-template: gemini-translator
      matchers:
      - uri:
          prefix: /gemini
        headers:
        - name: x-template
          value: translator
        - name: x-language
        - name: x-prompt
      forwardTo:
        pathRewrite: /v1beta/models/gemini-pro:generateContent
        hostRewrite: generativelanguage.googleapis.com
        destinations:
        - kind: EXTERNAL_SERVICE
          port:
            number: 443
          ref:
            name: gemini-externalservice
            namespace: ai-gateway-ws-config