apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gemini-client-routetable
  namespace: ai-gateway-ws-config
spec:
  hosts:
    - 'gemini-client.central.glooplatform.com'
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: eli5-client
      labels:
        oauth: gemini-client.central.glooplatform.com
      matchers:
      - uri:
          prefix: /eli5
      - uri:
          prefix: /callback
      forwardTo:
        destinations:
        - ref:
            name: gemini-eli5-client
            namespace: ai-client
            cluster: glooplatform-central
          port:
            number: 5000
    - name: translator-client
      labels:
        oauth: gemini-client.central.glooplatform.com
      matchers:
      - uri:
          prefix: /translate
      - uri:
          prefix: /callback
      forwardTo:
        destinations:
        - ref:
            name: gemini-translator-client
            namespace: ai-client
            cluster: glooplatform-central
          port:
            number: 5000