apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: gemini-catchall-rt
  namespace: ai-gateway-ws-config
  labels:
    llm-type: gemini
    prompt-template: "none"
spec:
  http:
  - name: catch-all
    matchers:
    - uri:
        prefix: /v1beta/models/gemini-pro:generateContent
    - uri:
        prefix: /gemini
    forwardTo:
      pathRewrite: /v1beta/models/gemini-pro:generateContent
      hostRewrite: generativelanguage.googleapis.com
      destinations:
      - kind: EXTERNAL_SERVICE
        port:
          number: 443
        ref:
          name: gemini-externalservice
          namespace: ai-gateway-ws-config
