apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: openai-system-user-input-rt
  namespace: ai-gateway-ws-config
spec:
  http:
    - name: system-user-input
      labels:
        prompt-template: system-user-input
      matchers:
      - uri:
          prefix: /openai
        headers:
        - name: x-api-key
        - name: x-system-prompt
        - name: x-user-prompt
      forwardTo:
        pathRewrite: /v1/chat/completions
        hostRewrite: api.openai.com
        destinations:
        - kind: EXTERNAL_SERVICE
          port:
            number: 443
          ref:
            name: openai-chatgpt
            namespace: ai-gateway-ws-config