apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: openai-catchall-rt
  namespace: ai-gateway-ws-config
spec:
  http:
    - name: catch-all
      matchers:
      - uri:
          prefix: /openai
      - uri:
          prefix: /v1/chat/completions
      forwardTo:
        pathRewrite: /v1/chat/completions
        hostRewrite: api.openai.com
        destinations:
        - kind: EXTERNAL_SERVICE
          port:
            number: 443
          ref:
            name: openai-chatgpt
            namespace: ai-gateway-ws-config
